name: express-aws CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install npm packages
        run: npm ci
      - name: Install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380
      - name: Run Test
        run: npm run test
      - name: test build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Set up known hosts
        run: |
          echo "${{secrets.SSH_KNWON_HOSTS}}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: SSH and deploy
        run: |
          ssh ${{secrets.SSH_USER_NAME}}@${{secrets.SSH_PUBLIC_IP}} "
            cd devops-practice
            git pull || exit 1
            npm install || exit 1
            npm run build || exit 1
            sudo pm2 reload all
            exit
          "
