name: express-aws CICD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build ant test with Docker Compose
        run: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
